### ISSUE TITLE
Uncaught TypeError: Cannot read property 'Menu' of undefined

### ISSUE THREAD

**Issue by dukedougal** [andrusieczko/ec2-browser#1]
I type "npm start" and the electron application starts OK. I see a window with the title "AWS EC2 Manager" and a button saying "Load AWS EC2 settings".

The console says 
Uncaught TypeError: Cannot read property 'Menu' of undefined app.js 319

var classNames = require('classnames');

var remote = electronRequire('electron').remote;
--> (this is line 319) var Menu = remote.Menu;
var MenuItem = remote.MenuItem;

The window that I typed "npm start" from says "Electron could not be found. No hard resets for you!" at the command line.

Any ideas?

thanks

**Comment by andrusieczko** [comment]
Hi @dukedougal,

Hahaha, you surprised me a lot! :) The project is ongoing, I should've written that :)

I started it 4 days ago as a way to learn Electron, React and all the fun stuff. But you made my day you already found it! :+1: 

You need to create your `aws-config.json` first, if you're not aware yet.

Regarding the issue, I'll check it in the evening.

Cheers,
Karol

**Comment by dukedougal** [comment]
Is it possible that line 318 should be 

var remote = electronRequire('remote');

instead of

var remote = electronRequire('electron').remote;

**Comment by andrusieczko** [comment]
Hey,

I think it can be either way... Anyway, I updated the code the way you suggested it and it seems to be working for me too.

That's the referential materials I'm basing on:
https://github.com/atom/electron/blob/master/docs/api/remote.md
http://electron.atom.io/docs/v0.27.0/api/remote/

Cheers,
Karol
