### ISSUE TITLE
Is this project in a working state?  What are the commands to install and run it?

### ISSUE THREAD

**Issue by dukedougal** [andrusieczko/ec2-browser#2]

**Comment by andrusieczko** [comment]
Hi @dukedougal,

I haven't finished it yet since it's Christmas/New Year's time :) but you can get it working.

Try to create `aws-config.json` file in a main folder with such a structure:

```
{
  "accessKeyId": "<your_access_key_id>",
  "secretAccessKey": "<your_secret_access_key>"
}
```

Then run `npm install` and `npm start` or `electron .`.

Please let me know if you have any problems with that.

**Comment by dukedougal** [comment]
I get the following errors when I run gulp...

PS C:\Users\me\devel\ec2-browser> gulp
[17:49:24] Using gulpfile ~\devel\ec2-browser\gulpfile
[17:49:24] Starting 'browserify'...
[17:49:24] Starting 'css'...
[17:49:24] Finished 'css' after 7.29 ms
[17:49:25]
app.js
    1:221  error  Missing semicolon  semi
    1:313  error  Missing semicolon  semi
    1:335  error  Missing semicolon  semi
    1:355  error  Missing semicolon  semi
    1:441  error  Missing semicolon  semi
  753:77   error  Missing semicolon  semi

✖ 6 problems (6 errors, 0 warnings)

events.js:141
      throw er; // Unhandled 'error' event
      ^
 ESLintError: Failed with 6 errors

**Comment by andrusieczko** [comment]
Hey,

I see the problem, can't help you right now.

Nevertheless, `gulp` is not required to run the project.
It's only required when you want to build the project.

Regards,
Karol

**Comment by dukedougal** [comment]
I think I got it going thanks for your help happy holidays!
